@startuml

class Bird {
    ~family :String
    ~specie : String
    ~commomName : String
    ~height : double
    ~year : int

    +toString() : String
}

class BirdApp {
    +{static} main(String[] args) : void
}

BirdApp ...> Bird

@enduml